package norswap.sigh.bytecode;

public final class SighRuntime
{
    /**
     * Concatenates two strings. Using this method in the generated bytecode is much simpler
     * than emitting a whole slew of instructions as Java does (see
     * https://www.guardsquare.com/en/blog/string-concatenation-java-9-untangling-invokedynamic).
     */
    public static String concat(String left, String right) {
        return left + right;
    }

    /**
     * Implementation of the Sigh {@code print} method, which prints the string to standard output
     * then returns it.
     *
     * <p>For now, only used to get a method handle for when {@code print} is used as a value,
     * but not actually used in method calls. Might change that in the future?
     */
    public static String print(String string) {
        System.out.println(string);
        return string;
    }
}
